### ISSUE TITLE
Pitch Deck feedback

### ISSUE THREAD

**Issue by sofa13** [SEGosaurus/SEGosaurus.github.io#1]
Hey Team #15 @DostZeroMachine @bijx @anthony-talevi @AustinTamb , 

This is Sophie, one of your TAs for SEG1911. This issue I opened is just an easy way for me to give you feedback for your pitch deck based on what you submitted for deliverable 4.

Based on what you submitted for deliverable 4, which was an html file (Pitch - Google slides.html), I can't view your pitch deck. This isn't a problem unless you want feedback. If you want feedback, could one of you reply back in this issue with a link or attachment of your pitch deck, and tag my github name @sofa13

Sophie

**Comment by bijx** [comment]
Hi Sophie,

We noticed our error right after we uploaded it, and I sent an email to Alex at his school email with the updated copy. Sorry for the misunderstanding

Regards,
Bijan Samiee
Team 15

Envoy? de mon iPhone

Le 14 nov. 2016 ? 15:19, Sophie Le Page <notifications@github.com<mailto:notifications@github.com>> a ?crit :

Hey Team #15 @DostZeroMachinehttps://github.com/DostZeroMachine @bijxhttps://github.com/bijx @anthony-talevihttps://github.com/anthony-talevi @AustinTambhttps://github.com/AustinTamb ,

This is Sophie, one of your TAs for SEG1911. This issue I opened is just an easy way for me to give you feedback for your pitch deck based on what you submitted for deliverable 4.

Based on what you submitted for deliverable 4, which was an html file (Pitch - Google slides.html), I can't view your pitch deck. This isn't a problem unless you want feedback. If you want feedback, could one of you reply back in this issue with a link or attachment of your pitch deck, and tag my github name @sofa13https://github.com/sofa13

Sophie

##

**Comment by sofa13** [comment]
Okay, no problem, so you guys already got feedback from Alex?

**Comment by bijx** [comment]
Yes, he replied and confirmed that he received the file. Thank you.

Envoy? de mon iPhone

Le 14 nov. 2016 ? 15:24, Sophie Le Page <notifications@github.com<mailto:notifications@github.com>> a ?crit :

Okay, no problem, so you guys already got feedback from Alex?

##

**Comment by sofa13** [comment]
Hey Team #15 @DostZeroMachine @bijx @anthony-talevi @AustinTamb ,

Since your team has been picked as one of the 5 finalists to present today, here's some more feedback on how I marked you when you guys presented last week!

[Team 15.docx](https://github.com/SEGosaurus/SEGosaurus.github.io/files/606569/Team.15.docx)

Good work, and good luck with presenting today :)

Sophie

**Comment by AustinTamb** [comment]
Project is done.
